version: '3.3'

services:
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver-gl
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/data
    environment:
      - NODE_ENV=production
    command: ["--verbose"]